export const vaultDocuments = [
  {
    id: "nms-master-overview",
    title: "Natural Medicinal Services (NMS)",
    filename: "Natural_Medicinal_Services_(NMS).pdf",
    type: "PDF",
    size: "8.6 MB",
    category: "Business & brand overview",
    description: "Edited NMS overview covering the organisation, brand context and strategic foundation.",
    url: "/manus-storage/Natural_Medicinal_Services_(NMS)_2c5b957b.pdf",
  },
  {
    id: "budget-roi-selector",
    title: "Budget & ROI Selector",
    filename: "NMS_Budget_and_ROI_Selector.xlsx",
    type: "XLSX",
    size: "29 KB",
    category: "Commercial planning",
    description: "Interactive budget and return-on-investment selector for executive scenario review.",
    url: "/manus-storage/NMS_Budget_and_ROI_Selector_27747512.xlsx",
  },
  {
    id: "relaunch-strategy-proposal",
    title: "Relaunch Strategy Proposal",
    filename: "NMS_Relaunch_Strategy_Proposal.pdf",
    type: "PDF",
    size: "41 KB",
    category: "Executive strategy",
    description: "Edited strategic proposal for the NMS relaunch, priorities and leadership decisions.",
    url: "/manus-storage/NMS_Relaunch_Strategy_Proposal_235b3231.pdf",
  },
  {
    id: "catalog-packaging-review",
    title: "Product Catalogue & Packaging Stakeholder Review",
    filename: "NMS_Product_Catalog_Packaging_Stakeholder_Review.pdf",
    type: "PDF",
    size: "773 KB",
    category: "Product & packaging",
    description: "Stakeholder review pack for catalogue structure, product presentation and packaging direction.",
    url: "/manus-storage/NMS_Product_Catalog_Packaging_Stakeholder_Review_f8543e25.pdf",
  },
  {
    id: "product-catalog-draft-v1",
    title: "Product Catalogue Draft V1",
    filename: "product catalog draft V1.pdf",
    type: "PDF",
    size: "993 KB",
    category: "Product catalogue",
    description: "Edited first-draft product catalogue for detailed range and content review.",
    url: "/manus-storage/product catalog draft V1_f027c744.pdf",
  },
  {
    id: "implementation-plan",
    title: "Complete Implementation & Project Management Plan",
    filename: "Complete Implementation & Project Management Plan.pdf",
    type: "PDF",
    size: "4.2 MB",
    category: "Delivery plan",
    description: "End-to-end implementation, governance, sequencing and project-management plan.",
    url: "/manus-storage/Complete Implementation & Project Management Plan_3c3dc2d0.pdf",
  },
  {
    id: "typography-asset-specification",
    title: "Standard Typography & Asset Specification",
    filename: "NMS_Standard_Typography_and_Asset_Specification.pdf",
    type: "PDF",
    size: "7.1 MB",
    category: "Brand system",
    description: "Edited typography, visual-system and asset-production specification for consistent rollout.",
    url: "/manus-storage/NMS_Standard_Typography_and_Asset_Specification_bcf82a27.pdf",
  },
  {
    id: "logo-strategy-brainstorm",
    title: "Logo Strategy & Brainstorm",
    filename: "NMS_Logo_Strategy_BrainstormJB3.pdf",
    type: "PDF",
    size: "4.2 MB",
    category: "Identity decisions",
    description: "Edited logo strategy and concept exploration prepared for leadership selection.",
    url: "/manus-storage/NMS_Logo_Strategy_BrainstormJB3_6a622bf4.pdf",
  },
] as const;

export type VaultDocumentId = (typeof vaultDocuments)[number]["id"];
